#!/usr/bin/env python3
"""Lay the A7 scope & sequence onto the 2026-27 Lake County calendar, one period per row.
Edit PLAN (in order) and re-run; the markdown table is regenerated from it.
Calendar: Aug 10 2026 - May 28 2027, holidays per the board-approved calendar (verify
against the school copy). Wednesdays are 43-minute periods: absorbed on the day, not planned."""
import datetime as d, json, re, os
HERE=os.path.dirname(os.path.abspath(__file__))
SK=json.load(open(os.path.join(HERE,"..","a7","reference","ixl_skills_by_lesson.json")))  # generated by tools/ixl_plan_from_pdf.py from IXL's printed skill plan
SMARTSCORE=67   # A7 students stop at a SmartScore of 67
THREAD_SKILLS={"T-A1":["14.1","14.2"],"T-A2":["14.3","14.4"],"T-B1":["16.1"],"T-B2":["16.2"],"T-C1":["17.1"],"T-C2":["17.2","17.3"]}
def lessons_for(code):
    if code in THREAD_SKILLS: return THREAD_SKILLS[code]
    m=re.match(r'^(\d+)\.(\d+)(?:[+–-](.*))?',code)
    if not m or code.endswith(("X1","X2","X")) : return []
    u=m.group(1); first=int(m.group(2)); rest=m.group(3)
    nums=[first]
    if rest:
        for part in re.split(r'[+–-]',rest):
            part=part.strip()
            if part.isdigit(): nums.append(int(part))
        if "–" in code:  # a range like 14.01–04
            nums=list(range(first,nums[-1]+1))
    return [f"{u}.{n}" for n in nums]
def ixl(code):
    """Ruling 28: every skill IXL lists for the lesson is REQUIRED — the numbered ones and the
    'also consider' ones alike. Nothing on the list is optional. Returns one list of (name, code),
    deduped by code, numbered skills first."""
    out=[]
    for L in lessons_for(code):
        v=SK.get(L,{"main":[],"also":[]})
        for x in v["main"]+v["also"]:
            if x["code"] not in [m[1] for m in out]: out.append((x["name"],x["code"]))
    return out
start=d.date(2026,9,23)          # first day after the Unit 2 exam (Sep 21-22)
end=d.date(2027,5,28)
hol={d.date(2026,10,12),d.date(2026,11,11),d.date(2027,1,18),d.date(2027,2,15),
     d.date(2027,3,5),d.date(2027,4,16),d.date(2027,1,4),d.date(2027,1,5)}
hol|={d.date(2026,11,x) for x in range(23,28)}
x=d.date(2026,12,21)
while x<=d.date(2027,1,1): hol.add(x); x+=d.timedelta(1)
hol|={d.date(2027,3,x) for x in range(22,27)}
days=[]; x=start
while x<=end:
    if x.weekday()<5 and x not in hol: days.append(x)
    x+=d.timedelta(1)

# (unit, lesson code, title, benchmark(s), kind) kind: L lesson, T woven thread, X exam, R review block
PLAN=[
 (3,"3.01","Product laws of exponents","7.NSO.1.1 · 8.NSO.1.3","L"),
 (3,"3.02","Quotient laws of exponents","7.NSO.1.1 · 8.NSO.1.3","L"),
 (3,"3.03","Exponential expressions","7.NSO.1.1 · 8.NSO.1.3","L"),
 (3,"3.04","Negative exponent law","8.NSO.1.3","L"),
 (3,"3.05","Applying exponent laws","8.NSO.1.3","L"),
 (3,"3.06+07","Evaluating and equivalent expressions with integer exponents","8.NSO.1.3","L"),
 (3,"T-A1","Thread A: the same laws with variable bases (14.1–14.2)","8.AR.1.1","T"),
 (3,"T-A2","Thread A: negative exponents and multiple laws, variable bases (14.3–14.4)","8.AR.1.1","T"),
 (3,"3.08","Large numbers in scientific notation","8.NSO.1.4","L"),
 (3,"3.09","Small numbers in scientific notation; how many times larger","8.NSO.1.4","L"),
 (3,"3.X1","Unit 3 exam, day 1","","X"),
 (3,"3.X2","Unit 3 exam, day 2","","X"),
 (4,"4.01","Add and subtract in scientific notation","8.NSO.1.5","L"),
 (4,"4.02+03","Multiply and divide in scientific notation","8.NSO.1.5","L"),
 (4,"4.04","Real-world scientific notation; significant digits","8.NSO.1.6","L"),
 (4,"4.05","Expressions with radicals (perfect squares to 225, cubes −125 to 125)","8.NSO.1.7","L"),
 (4,"4.06","Order of operations with exponents and radicals","8.NSO.1.7","L"),
 (4,"4.07+08","Real-world order-of-operations problems","8.NSO.1.7","L"),
 (4,"4.X1","Unit 4 exam, day 1","","X"),
 (4,"4.X2","Unit 4 exam, day 2","","X"),
 (5,"5.01","Scale drawings","7.GR.1.5","L"),
 (5,"5.02+03","Scale factor: perimeter and area (k and k²)","7.GR.1.5","L"),
 (5,"5.04","Real-world scale drawings","7.GR.1.5","L"),
 (5,"5.06+07","Converting length across systems; currency","7.AR.3.3","L"),
 (5,"5.08+09","Converting mass, area and volume across systems","7.AR.3.3","L"),
 (5,"5.10+11","Multi-step proportion problems","7.AR.3.3 · 7.AR.4.5","L"),
 (5,"5.X1","Unit 5 exam, day 1","","X"),
 (5,"5.X2","Unit 5 exam, day 2","","X"),
 (6,"6.01+02","Triangle Inequality Theorem; converse of the Pythagorean Theorem","8.GR.1.3","L"),
 (6,"6.03","Pythagorean Theorem (memorize)","8.GR.1.1","L"),
 (6,"6.04","Pythagorean Theorem in real-world problems","8.GR.1.1","L"),
 (6,"6.05","Distance on the coordinate plane","8.GR.1.2","L"),
 (6,"6.06","Real-world coordinate-plane problems; perimeter","8.GR.1.2","L"),
 (6,"T-B1","Thread B: angle pairs — supplementary, complementary, vertical, adjacent (16.1)","8.GR.1.4","T"),
 (6,"T-B2","Thread B: interior and exterior angles of a triangle (16.2)","8.GR.1.5","T"),
 (6,"6.07+08","Similar triangles; indirect measurement","8.GR.2.4","L"),
 (6,"6.X1","Unit 6 exam, day 1","","X"),
 (6,"6.X2","Unit 6 exam, day 2","","X"),
 (7,"7.01","Graphing proportional relationships","7.AR.4.3","L"),
 (7,"7.02+03","Constant of proportionality (table, graph, description)","7.AR.4.2","L"),
 (7,"7.04","Is it proportional?","7.AR.4.1 · 8.AR.3.1","L"),
 (7,"7.05+06","Equations of proportional relationships; translating representations","7.AR.4.4","L"),
 (7,"7.07","Comparing proportional relationships","7.AR.4.5","L"),
 (7,"7.X1","Unit 7 exam, day 1","","X"),
 (7,"7.X2","Unit 7 exam, day 2","","X"),
 (0,"PM2-R1","PM2 review 1: number system, exponents, scientific notation (whiteboards)","8.NSO.1.1–1.7","R"),
 (0,"PM2-R2","PM2 review 2: equations, inequalities, Pythagorean, angles (whiteboards)","8.AR.2 · 8.GR.1","R"),
 (0,"PM2-R3","PM2 review 3: proportional → linear preview; mixed FAST-shaped round","8.AR.3 · 8.AR.1.1","R"),
 (8,"8.01+02","Circle relationships; circumference","7.GR.1.3","L"),
 (8,"8.03","Radius and diameter from circumference","7.GR.1.3","L"),
 (8,"8.04+05","Area of a circle","7.GR.1.4","L"),
 (8,"8.06","Circumference and area problems; sectors","7.GR.1.4","L"),
 (8,"8.08+09","Sectors and circle graphs","7.GR.1.4 · 7.DP.1.4","L"),
 (9,"9.01+02","Surface area of cylinders from nets","7.GR.2.1 · 7.GR.2.2","L"),
 (9,"9.03+04+05","Volume of cylinders; problems","7.GR.2.3","L"),
 (9,"8/9.X1","Units 8–9 exam, day 1","","X"),
 (9,"8/9.X2","Units 8–9 exam, day 2","","X"),
 (10,"10.01","Proportional relationships revisited (linear ⇒ proportional?)","8.AR.3.1","L"),
 (10,"10.02+03","Slope from two points, graphs, tables","8.AR.3.2","L"),
 (10,"10.04","Slope in context","8.AR.3.2 · 8.AR.3.5","L"),
 (10,"10.05","Slope-intercept form; graph a line","8.AR.3.4","L"),
 (10,"10.06","Graphing from tables and contexts","8.AR.3.4","L"),
 (10,"10.07+08","Interpreting slope and intercept (graphs, equations, tables, descriptions; F↔C)","8.AR.3.5","L"),
 (10,"10.09","Writing equations of lines","8.AR.3.3","L"),
 (10,"10.10","Writing equations for contexts; lines of fit preview","8.AR.3.3 · 8.AR.3.5","L"),
 (10,"10.X1","Unit 10 exam, day 1","","X"),
 (10,"10.X2","Unit 10 exam, day 2","","X"),
 (11,"11.01","Equations with like terms and the distributive property","8.AR.2.1","L"),
 (11,"11.02","Variables on both sides","8.AR.2.1","L"),
 (11,"11.03","One, none, infinitely many solutions","8.AR.2.1","L"),
 (11,"11.04","Multi-step equations","8.AR.2.1","L"),
 (11,"11.05+06","Systems: which points are solutions; how many solutions","8.AR.4.1 · 8.AR.4.2","L"),
 (11,"11.07","Solving systems by graphing","8.AR.4.3","L"),
 (11,"11.08","Systems in context (approximate solutions)","8.AR.4.3","L"),
 (11,"11.X1","Unit 11 exam, day 1","","X"),
 (11,"11.X2","Unit 11 exam, day 2","","X"),
 (12,"12.01+02","Relations; domain and range","8.F.1.1","L"),
 (12,"12.03","Is it a function?","8.F.1.1","L"),
 (12,"12.04+05","Describing graphs: increasing, decreasing, constant","8.F.1.3","L"),
 (12,"12.06","Sketching graphs from descriptions","8.F.1.3","L"),
 (12,"12.07","Functions from equations, tables, graphs","8.F.1.2","L"),
 (12,"12.08+09","Is it linear? (graphs, equations, tables)","8.F.1.2 · 8.AR.3.1","L"),
 (12,"12.X1","Unit 12 exam, day 1","","X"),
 (12,"12.X2","Unit 12 exam, day 2","","X"),
 (13,"13.01+02+03","Choosing and creating displays (numerical, categorical)","7.DP.1.5","L"),
 (13,"13.04+05","Bivariate data; line graphs","8.DP.1.1","L"),
 (13,"13.06","Scatter plots and association","8.DP.1.1 · 8.DP.1.2","L"),
 (13,"13.07+08","Lines of fit; outliers","8.DP.1.3 · 8.DP.1.2","L"),
 (13,"13.09","Interpreting the equation of a line of fit","8.DP.1.3 · 8.AR.3.5","L"),
 (13,"T-C1","Thread C: sample spaces of repeated experiments (17.1)","8.DP.2.1","T"),
 (13,"T-C2","Thread C: theoretical probability of repeated experiments (17.2–17.3)","8.DP.2.2","T"),
 (13,"13.X1","Unit 13 exam, day 1","","X"),
 (13,"13.X2","Unit 13 exam, day 2","","X"),
 (14,"14.01–04","Exponent laws with variable bases — consolidation of Thread A","8.AR.1.1","L"),
 (14,"14.05+06","Multiplying a monomial by a linear expression","8.AR.1.2","L"),
 (14,"14.07+08","Factoring a common monomial","8.AR.1.3","L"),
 (14,"14.X1","Unit 14 exam, day 1","","X"),
 (14,"14.X2","Unit 14 exam, day 2","","X"),
 (15,"15.01","Slides, flips, spins","8.GR.2.1","L"),
 (15,"15.02+03","Reflections, rotations, translations — identify and describe","8.GR.2.1","L"),
 (15,"15.03b","Translations on the coordinate plane","8.GR.2.3","L"),
 (15,"15.04","Reflections on the coordinate plane","8.GR.2.3","L"),
 (15,"15.05","Rotations on the coordinate plane (about the origin)","8.GR.2.3","L"),
 (15,"15.06","Describing rigid transformations; congruence","8.GR.2.1 · 8.GR.2.3","L"),
 (15,"15.07+09","Dilations and scale factor","8.GR.2.2","L"),
 (15,"15.08","Dilations on the coordinate plane (centered at the origin)","8.GR.2.3","L"),
 (16,"16.01+02","Angle relationships — consolidation of Thread B","8.GR.1.4 · 8.GR.1.5","L"),
 (16,"16.03+04","Interior angles of polygons","8.GR.1.6","L"),
 (16,"15/16.X1","Units 15–16 exam, day 1","","X"),
 (16,"15/16.X2","Units 15–16 exam, day 2","","X"),
 (17,"17.01–03","Repeated experiments — consolidation of Thread C","8.DP.2.1 · 8.DP.2.2","L"),
 (17,"17.04–06","Predictions from theoretical probability","8.DP.2.3","L"),
 (17,"17.X1","Unit 17 exam, day 1","","X"),
 (17,"17.X2","Unit 17 exam, day 2","","X"),
]
# Ruling 27, as amended for A7 by Croix on 20 September: *"No review day, keep the reteach days.
# M7 has less content and can absorb extra days."* So A7 gets NO per-unit review day before the
# test — the Unit Review document goes home as practice instead — and the post-exam reteach day
# stays. The two test days still obey the rest of ruling 27 (day 1 a Monday or a Thursday, day 2
# the next school day, never straddling a weekend or a break); a spiral day absorbs any slack.
P2=[]
for r in PLAN:
    P2.append(r)
    # one flex day after every exam: reteach from exam evidence, or absorb a lost day
    if r[4]=="X" and r[1].endswith("X2") and r[0] in (3,4,6,9,10,11,12):   # not after 5 (Grade 7 unit), 7 (PM2 review follows), 13 (keeps Unit 14 whole before spring break); Q4's buffer is the PM3 review block
        P2.append((r[0],"flex","Flex day — reteach from exam evidence, or absorb a lost day","","F"))
PLAN=P2

# ---- the plan follows the class (Croix, 4 October 2026) ------------------------------------------
# "I need the plan to be fluid and adjust on the fly." The dates are no longer typed or fixed: they
# are what the kit's engine (a7/build/lib/flow.py — the same rules the console runs on the panel)
# gives when it lays PLAN, in order, onto the school days that are left after the as-run log
# (a7/reference/A7 As Run 2026-27.csv) has taken out the days that went to something else.
# His rule for a class that is behind: push everything back — flex and spiral days absorb the loss
# first, then the tests move to the next Monday or Thursday.
#   Ruling 27 (exam rule): day 1 is a Monday or a Thursday (so day 2 is never a Wednesday) and day 2
#   is the very next calendar day, so the two halves never straddle a weekend or a break; a spiral
#   day fills whatever has to pass first.
import importlib.util as _ilu
_sp=_ilu.spec_from_file_location("flow",os.path.join(HERE,"..","a7","build","lib","flow.py"))
flow=_ilu.module_from_spec(_sp); _sp.loader.exec_module(flow)
LOG_PATH=os.path.join(HERE,"..","a7","reference","A7 As Run 2026-27.csv")
QUARTERS={d.date(2026,10,9):"Q1",d.date(2026,12,18):"Q2",d.date(2027,3,4):"Q3",d.date(2027,5,28):"Q4"}
CONTENT_ENDS=d.date(2027,4,30)   # new content finishes before the PM3 window opens (May 3)
SPIRAL=("Spiral day — mixed retrieval from the unit just finished and the two before it","","S")
pm3=d.date(2027,5,3)
cats=["NSO and probability","algebraic reasoning (expressions, equations, systems)","linear relationships, functions, data","geometric reasoning"]
PM3_WINDOW="May 3–28: PM3 window (school date TBD). Content finishes Apr 30, so the whole window is free: PM3 review before the test — mixed FAST-shaped whiteboard rounds, one reporting category per question — and the Algebra 1 bridge after it (operations with radicals, point-slope and standard form, systems by substitution)"
def _item(r):
    u,code,title,bm,kind=r
    it={"kind":kind,"code":code,"title":title,"unit":u,"bm":bm}
    if kind=="X" and code.endswith("X1"): it["examIn"]=0
    if kind=="F": it["absorb"]=True
    return it
FLOW={"days":[x.isoformat() for x in days],"breaks":[],
      "rules":{"exam":{"weekdays":[0,3],"minBeforeBreak":0},
               "filler":{"unit":"next","entry":{"kind":SPIRAL[2],"code":"spiral","title":SPIRAL[0],"bm":SPIRAL[1]}}},
      "tail":[{"before":pm3.isoformat(),"count":True,"code":"PM3-R{n}","title":"PM3 review {n}: {t}","titles":cats,
               "titleRest":"mixed FAST-shaped rounds, one category per whiteboard question","entry":{"kind":"R","unit":0,"bm":"all"}},
              {"entry":{"kind":"W","code":"PM3","unit":0,"title":PM3_WINDOW,"bm":"912.NSO.1.4 · 912.AR.2.2 · 912.AR.9.1"}}],
      "items":[_item(r) for r in PLAN],"blocked":{}}
flow.baseline(FLOW)
LOG=flow.read_log(LOG_PATH)
flow.apply_log(FLOW,LOG,{"review":"Extra review day — no new lesson","off":"No class"})
LAID=flow.lay(FLOW)
if LAID["left"]:
    raise SystemExit("A7 plan: the year does not hold the sequence — no day is left for "
                     +", ".join(FLOW["items"][k]["code"] for k in LAID["left"])+". Cut or merge something in PLAN, or free a day in the log.")
BLOCKED_KIND={flow.EXTRA:"E",flow.OFF:"O"}      # an extra review / catch-up day; no class at all
rows=[]; n=0
for r in LAID["rows"]:
    e=r["entry"]; dt=d.date.fromisoformat(r["date"])
    if r["src"]=="blocked":
        rows.append((dt,e.get("unit") or 0,e["kind"],e["title"],"",BLOCKED_KIND[e["kind"]]))
    elif e["code"]=="PM3":
        if not any(q[2]=="PM3" for q in rows): rows.append((dt,0,"PM3",e["title"],e["bm"],"W"))   # one row for the whole window
    else:
        rows.append((dt,e["unit"],e["code"],e["title"],e["bm"],e["kind"]))
        if e["code"].startswith("PM3-R"): n+=1
def _seq(i):
    """The next row after i that the sequence owns (a day off does not interrupt a run of lessons)."""
    j=i+1
    while j<len(rows) and rows[j][5] in ("E","O"): j+=1
    return j
def run_end(i):
    """Ruling 28: lessons in a row with the same skills are one assignment. → the last row of the run."""
    sk=ixl(rows[i][2]); end=i
    while sk and _seq(end)<len(rows) and ixl(rows[_seq(end)][2])==sk: end=_seq(end)
    return end
def due(i):
    """The date the skills assigned on row i are due: the first day the class meets after the run."""
    if not ixl(rows[i][2]): return None
    nxt=[r[0] for r in rows[run_end(i)+1:] if r[5] not in ("W","O")]
    return nxt[0] if nxt else None
def report():
    """What the log moved, in words (the end of the scope document, and stderr)."""
    if not LOG: return []
    ch=flow.changes(FLOW,LAID); out=["","## The plan follows the class","",
        "The dates above are laid out from the sequence of lessons, the school calendar and the as-run log "
        "(`A7 As Run 2026-27.csv`): a lost day is one line in the log, and everything after it moves. Rule (Croix, 4 October 2026): "
        "push everything back — flex and spiral days absorb the loss first, then tests move to the next Monday or Thursday.",""]
    out.append("**The log:**"); out.append("")
    said={e["date"]:(f"the class began {e['what']}" if e["what"] not in ("review","off") else FLOW["blocked"][e["date"]]["title"]) for e in LOG}
    for x,bl in FLOW["blocked"].items():
        if bl.get("unrecorded"): said[x]="a day off the plan that the log does not name (the class was further behind than the log explains)"
    for x in sorted(said): out.append(f"- {d.date.fromisoformat(x).strftime('%a %b %d %Y')}: {said[x]}")
    out+=["","**What moved:**",""]
    f=lambda s: d.date.fromisoformat(s).strftime('%a %b %d')
    for it,base,now,by in ch["moved"]:
        if it["kind"]=="X" and it["code"].endswith("X1"):
            q0=next(q for e,q in sorted(QUARTERS.items()) if d.date.fromisoformat(base)<=e); q1=next(q for e,q in sorted(QUARTERS.items()) if d.date.fromisoformat(now)<=e)
            out.append(f"- {it['title'].replace(', day 1','')}: {f(base)} → **{f(now)}** ({by:+d} school days)"+(f" — **now in {q1}, was in {q0}**" if q0!=q1 else ""))
    gone=[it for it in FLOW["items"] if it.get("gone")]
    if gone: out.append("- covered on a day the log does not name: "+", ".join(it["code"] for it in gone))
    flex=[it for it in FLOW["items"] if it["kind"]=="F"]
    out.append(f"- flex days absorbed: {len(ch['dropped'])} of {len(flex)}"+(" (after Unit "+", ".join(str(it['unit']) for it in ch['dropped'])+")" if ch['dropped'] else "")+f"; {len(flex)-len(ch['dropped'])} left to absorb later losses")
    last=max((r[0] for r in rows if r[5] in ("L","T","X")),default=None)
    if last:
        late=last>CONTENT_ENDS
        out.append(f"- the last day of content and tests: {last.strftime('%a %b %d')}"+(f" — **{sum(1 for x in days if CONTENT_ENDS<x<=last)} school days past Apr 30, inside the PM3 window**" if late else f" (content must end by Apr 30); PM3 review days before the window: {n}"))
    return out
if __name__=="__main__":
    import sys
    TABLE=["| Date | Day | Unit | Lesson | What is taught | Benchmark | IXL skills — all required, code | Due |",
           "|---|---|---|---|---|---|---|---|"]
    for i,(dt,u,code,title,bm,kind) in enumerate(rows):
        wd=dt.strftime("%a")
        flag=" (43 min)" if wd=="Wed" else ""
        mark={"T":"**thread** ","X":"**exam** ","R":"**review** ","F":"*flex* ","S":"*spiral* ","W":"","E":"*extra* ","O":"*off* "}.get(kind,"")
        sk=ixl(code)
        # ruling 28: lessons in a row with the same skills are one assignment, due after the last
        # of them (run_end and due above — the due-date sheet below and the spine use the same two)
        dd=due(i).strftime('%b %d') if due(i) else ""
        M="; ".join(f"{n} — {c}" for n,c in sk)
        TABLE.append(f"| {dt.strftime('%b %d')} | {wd}{flag} | {u if u else ''} | {code} | {mark}{title} | {bm} | {M} | {dd} |")
    TABLE+=report()
    print("\n".join(TABLE))
    with open(os.path.join(HERE,"..","a7","reference","A7 Scope and Sequence 2026-27.md"),"w",encoding="utf-8") as f:
        f.write("\n".join(TABLE)+"\n")
    # student-facing due-date sheet (ruling 28)
    with open(os.path.join(HERE,"..","a7","reference","A7 IXL Due Dates 2026-27.md"),"w") as f:
        f.write(f"# A7 — IXL assignments and due dates, 2026–27\n\n"
                f"Each class day ends with five minutes of IXL. That block is the **start** of the assignment, not the whole of it; "
                f"whatever is not finished in class is that night's practice.\n\n"
                f"**Every skill listed for a lesson is required. Nothing on this sheet is optional.** "
                f"Done means a **SmartScore of {SMARTSCORE}** on every listed skill.\n\n"
                f"Assigned the day of the lesson, **due at the start of the next class**. When two or more lessons in a row use the "
                f"same skills, they are one assignment covering the run, due after the last lesson in it.\n\n"
                f"The three-character code after each skill is what you type into IXL's search box.\n\n"
                f"| Assigned | Lesson(s) | Skills — all required, to SmartScore {SMARTSCORE} | Due |\n|---|---|---|---|\n")
        teach=[(i,r) for i,r in enumerate(rows) if ixl(r[2])]
        j=0
        while j<len(teach):
            i0,r0=teach[j]; skills=ixl(r0[2])
            k2=j
            while k2+1<len(teach) and ixl(teach[k2+1][1][2])==skills and teach[k2+1][0]==_seq(teach[k2][0]):
                k2+=1
            i1,r1=teach[k2]
            due_=due(i0).strftime('%a %b %d') if due(i0) else ""
            lab=f"{r0[2]} {r0[3]}" if k2==j else f"{r0[2]}–{r1[2]} ({k2-j+1} lessons) {r0[3]}"
            when=r0[0].strftime('%a %b %d') if k2==j else f"{r0[0].strftime('%a %b %d')}"
            S="; ".join(f"{n} ({c})" for n,c in skills)
            f.write(f"| {when} | {lab} | {S} | {due_} |\n")
            j=k2+1
    print(f"\nPlanned periods: {len(rows)} of {len(days)} available Sep 23–May 28; PM3 review days: {n}", file=sys.stderr)
    for dt,u,code,title,bm,kind in rows:
        if code.endswith("X1") or code=="17.X" or code.startswith("PM"):
            pass
    import collections
    firsts={}
    for dt,u,code,title,bm,kind in rows:
        if u and u not in firsts: firsts[u]=dt
    print("Unit starts:", {k:v.strftime('%b %d') for k,v in firsts.items()}, file=sys.stderr)
