#!/usr/bin/env python3
"""Build `A7 Scope and Sequence 2026-27.xlsx`: the year's calendar with a link to every shipped
document, so the plan and the packages are one click apart. Reads the calendar table
(`a7/reference/A7 SCOPE AND SEQUENCE 2026-27.md`, generated by scope_calendar.py) and the
package folders; links point at the GitHub repository, where a PDF opens in the browser.

    python3 tools/scope_workbook.py [out.xlsx]

Rerun after any unit is built or any package changes; the file records the commit it was built from.
"""
import os, re, sys, glob, datetime, subprocess, urllib.parse
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
CAL = os.path.join(ROOT, "a7", "reference", "A7 SCOPE AND SEQUENCE 2026-27.md")
PKG = os.path.join(ROOT, "a7", "packages")
REPO = "https://github.com/croix18/croix18-windy-hill-a7"
FONT = "Arial"

UNIT_TITLES = {1: "Equations and Inequalities", 2: "Real Numbers, Square Roots and Cube Roots",
               3: "Exponents and Scientific Notation", 4: "Solving Problems with Rational Numbers",
               5: "Solving Multi-Step Problems with Proportional Relationships", 6: "Relationships in Triangles",
               7: "Representing Proportional Relationships", 8: "Relationships in Circles", 9: "Surface Area and Volume",
               10: "Linear Relationships", 11: "Solving Equations and Systems of Equations", 12: "Functions",
               13: "Representing Data", 14: "Equivalent Algebraic Expressions", 15: "Transformations",
               16: "Properties and Theorems of Angles", 17: "Probability"}
# calendar lesson code -> file stem in the package (merged periods and threads carry one stem)
STEM = {"3.06+07": "3.06", "T-A1": "3.T1", "T-A2": "3.T2", "4.02+03": "4.02", "4.07+08": "4.07"}
MONTHS = {m: i for i, m in enumerate(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"], 1)}


def gh(path, kind="blob"):
    """A GitHub link to a file (blob) or folder (tree) under the repository root."""
    return f"{REPO}/{kind}/main/" + urllib.parse.quote(path.replace(os.sep, "/"), safe="/")


def pkg_folder(unit):
    hits = glob.glob(os.path.join(PKG, f"A7 Unit {unit} - *"))
    return hits[0] if hits else None


def rel(path):
    return os.path.relpath(path, ROOT)


def date_of(s):
    mon, day = s.split()
    m = MONTHS[mon]
    return datetime.date(2026 if m >= 7 else 2027, m, int(day))


def read_calendar():
    rows = []
    for ln in open(CAL, encoding="utf-8"):
        cells = [c.strip() for c in ln.strip().strip("|").split("|")]
        if len(cells) != 8 or cells[0] in ("Date", "---") or cells[0].startswith("---"):
            continue
        date, day, unit, code, taught, bm, ixl, due = cells
        rows.append(dict(date=date_of(date), day=day, unit=int(unit) if unit else None, code=code,
                         taught=re.sub(r"^\*{1,2}\w+\*{1,2}\s*", "", taught).replace("*", ""),   # drop the **exam** / *spiral* tag; the Lesson column carries it
                         benchmark=bm, ixl=ixl, due=date_of(due) if re.fullmatch(r"\w{3} \d{1,2}", due) else due))
    return rows


def lesson_files(unit, code):
    """The documents a lesson row links to: {label: (text, url)} or None where nothing is built."""
    folder = pkg_folder(unit) if unit else None
    if not folder:
        return None
    U = unit
    stem = STEM.get(code, code)
    def f(sub, name):
        p = os.path.join(folder, sub, name)
        return (os.path.basename(name), gh(rel(p))) if os.path.exists(p) else None
    kind = code
    if re.fullmatch(r"\d+\.X\d", code):                       # exam day
        return {"Slides (PDF)": f("PDFs/Assessments", f"A7 {U}  Unit Assessment.pdf") and ("Unit Assessment", f("PDFs/Assessments", f"A7 {U}  Unit Assessment.pdf")[1]),
                "Answer Keys": (("Answer Keys", gh(rel(os.path.join(folder, "Answer Keys")), "tree"))),
                "Unit folder": ("folder", gh(rel(folder), "tree"))}
    if code == "spiral":
        rv = f("PDFs/Assessments", f"A7 {U}  Unit Review.pdf")
        return {"Slides (PDF)": rv and ("Unit Review", rv[1]),
                "Answer Keys": ("Answer Keys", gh(rel(os.path.join(folder, "Answer Keys")), "tree")),
                "Unit folder": ("folder", gh(rel(folder), "tree"))}
    if code == "flex":
        return {"Unit folder": ("folder", gh(rel(folder), "tree"))}
    if not re.fullmatch(r"[\d.T+A-]+", code):
        return {"Unit folder": ("folder", gh(rel(folder), "tree"))}
    out = {}
    for label, sub, name in [("Slides (PDF)", "PDFs/Slides", f"A7 {stem}  Slides.pdf"),
                             ("Slides (PowerPoint)", "Slides", f"A7 {stem}  Slides.pptx"),
                             ("Teacher Edition", "PDFs/Teacher Editions", f"A7 {stem}  Teacher Edition.pdf"),
                             ("Lesson Plan", "PDFs/Lesson Plans", f"A7 {stem}  Lesson Plan.pdf"),
                             ("Question Bank", "PDFs/Question Banks", f"A7 {stem}  Question Bank.pdf"),
                             ("Independent Set", "PDFs/Independent Sets", f"A7 {stem}  Independent Set.pdf")]:
        hit = f(sub, name)
        if hit:
            out[label] = ("open", hit[1])
    if not out:
        return None
    out["Answer Keys"] = ("Answer Keys", gh(rel(os.path.join(folder, "Answer Keys")), "tree"))
    out["Unit folder"] = ("folder", gh(rel(folder), "tree"))
    return out


# ---------------------------------------------------------------- styles
HEAD_FILL = PatternFill("solid", fgColor="1F3864")
HEAD_FONT = Font(name=FONT, bold=True, color="FFFFFF", size=10)
BODY = Font(name=FONT, size=10)
LINK = Font(name=FONT, size=10, color="0563C1", underline="single")
DIM = Font(name=FONT, size=10, color="808080", italic=True)
BOLD = Font(name=FONT, size=10, bold=True)
EXAM_FILL = PatternFill("solid", fgColor="FCE4D6")
SPIRAL_FILL = PatternFill("solid", fgColor="EDEDED")
UNIT_FILLS = ["FFFFFF", "F2F7FC"]
THIN = Side(style="thin", color="D9D9D9")
BORDER = Border(bottom=THIN)


def header(ws, cols, row=1):
    for i, c in enumerate(cols, 1):
        cell = ws.cell(row=row, column=i, value=c)
        cell.font = HEAD_FONT; cell.fill = HEAD_FILL
        cell.alignment = Alignment(vertical="center", wrap_text=True)
    ws.row_dimensions[row].height = 30


def put(ws, r, c, value, font=BODY, link=None, fill=None, wrap=False, fmt=None, align=None):
    cell = ws.cell(row=r, column=c, value=value)
    cell.font = font
    if link:
        cell.hyperlink = link; cell.font = LINK
    if fill:
        cell.fill = fill
    cell.alignment = Alignment(vertical="top", wrap_text=wrap, horizontal=align)
    cell.border = BORDER
    if fmt:
        cell.number_format = fmt
    return cell


def commit():
    try:
        return subprocess.run(["git", "-C", ROOT, "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()
    except Exception:
        return "?"


def build(out):
    rows = read_calendar()
    wb = Workbook()

    # ------------------------------------------------------------ Scope & Sequence
    ws = wb.active; ws.title = "Scope & Sequence"
    cols = ["Date", "Day", "Unit", "Lesson", "What is taught", "Benchmark", "IXL skills — all required, code",
            "IXL due", "Slides (PDF)", "Slides (PowerPoint)", "Teacher Edition", "Lesson Plan", "Question Bank",
            "Independent Set", "Answer Keys", "Unit folder"]
    header(ws, cols)
    link_cols = cols[8:]
    r = 2
    for row in rows:
        files = lesson_files(row["unit"], row["code"])
        is_exam = bool(re.fullmatch(r"\d+\.X\d", row["code"]))
        fill = EXAM_FILL if is_exam else (SPIRAL_FILL if row["code"] in ("spiral", "flex") or row["code"].startswith("PM") else PatternFill("solid", fgColor=UNIT_FILLS[(row["unit"] or 0) % 2]))
        put(ws, r, 1, row["date"], fill=fill, fmt="ddd d mmm yyyy")
        put(ws, r, 2, row["day"], fill=fill)
        put(ws, r, 3, row["unit"], fill=fill, align="center")
        put(ws, r, 4, row["code"], fill=fill, font=BOLD)
        put(ws, r, 5, row["taught"], fill=fill, wrap=True)
        put(ws, r, 6, row["benchmark"], fill=fill, wrap=True)
        put(ws, r, 7, row["ixl"], fill=fill, wrap=True)
        put(ws, r, 8, row["due"], fill=fill, fmt="d mmm" if not isinstance(row["due"], str) else None)
        for j, label in enumerate(link_cols, 9):
            hit = files.get(label) if files else None
            if hit:
                put(ws, r, j, hit[0], link=hit[1], fill=fill)
            elif files is None and row["unit"] and not pkg_folder(row["unit"]):
                put(ws, r, j, "not built yet" if j == 9 else "", font=DIM, fill=fill)
            else:
                put(ws, r, j, "", fill=fill)
        r += 1
    widths = [16, 14, 5, 9, 46, 20, 44, 9, 13, 16, 14, 12, 13, 14, 12, 10]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w
    ws.freeze_panes = "E2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(cols))}{r - 1}"
    last_row = r - 1

    # ------------------------------------------------------------ Units
    wu = wb.create_sheet("Units")
    ucols = ["Unit", "Title", "First day", "Last day", "Periods", "Status", "Package folder", "START HERE",
             "Reference Sheet", "Unit Review", "Unit Assessment", "Answer Keys", "Slides folder"]
    header(wu, ucols)
    r = 2
    for u in range(1, 18):
        folder = pkg_folder(u)
        dates = [x["date"] for x in rows if x["unit"] == u]
        put(wu, r, 1, u, align="center", font=BOLD)
        put(wu, r, 2, UNIT_TITLES[u], wrap=True)
        if dates:
            put(wu, r, 3, min(dates), fmt="d mmm yyyy"); put(wu, r, 4, max(dates), fmt="d mmm yyyy")
            put(wu, r, 5, f"=COUNTIF('Scope & Sequence'!$C$2:$C${last_row},A{r})", align="center")
        else:
            put(wu, r, 3, "taught before 23 Sep", font=DIM); put(wu, r, 4, "", font=DIM); put(wu, r, 5, "", font=DIM)
        if folder:
            status = "built, audited 21 Sep 2026" if u in (3, 4) else "built (before the spec system; not covered by the checks)"
            put(wu, r, 6, status, wrap=True)
            put(wu, r, 7, "folder", link=gh(rel(folder), "tree"))
            sh = os.path.join(folder, "00 - START HERE.md")
            put(wu, r, 8, "open", link=gh(rel(sh))) if os.path.exists(sh) else put(wu, r, 8, "")
            for j, (sub, name) in enumerate([("PDFs/Handouts", f"A7 {u}  Reference Sheet.pdf"), ("PDFs/Assessments", f"A7 {u}  Unit Review.pdf"),
                                              ("PDFs/Assessments", f"A7 {u}  Unit Assessment.pdf")], 9):
                p = os.path.join(folder, sub, name)
                put(wu, r, j, "open", link=gh(rel(p))) if os.path.exists(p) else put(wu, r, j, "")
            put(wu, r, 12, "folder", link=gh(rel(os.path.join(folder, "Answer Keys")), "tree"))
            put(wu, r, 13, "folder", link=gh(rel(os.path.join(folder, "PDFs", "Slides")), "tree"))
        else:
            put(wu, r, 6, "not built yet", font=DIM)
            for j in range(7, 14):
                put(wu, r, j, "")
        r += 1
    put(wu, r + 1, 1, "Periods is a live count of this unit's rows on the Scope & Sequence sheet (exam, spiral and flex days included).", font=DIM)
    for i, w in enumerate([6, 44, 13, 13, 9, 34, 14, 12, 15, 12, 16, 12, 13], 1):
        wu.column_dimensions[get_column_letter(i)].width = w
    wu.freeze_panes = "C2"

    # ------------------------------------------------------------ Units 1–2 decks
    wd = wb.create_sheet("Units 1–2 decks")
    dcols = ["Unit", "Lesson", "Slides (PDF)", "Teacher Edition", "Question Bank", "Question Bank – Additional", "Answer Keys"]
    header(wd, dcols)
    r = 2
    for u in (1, 2):
        folder = pkg_folder(u)
        if not folder:
            continue
        for pdf in sorted(glob.glob(os.path.join(folder, "PDFs", "Slides", "A7 *  Slides.pdf"))):
            stem = re.match(r"A7 (\S+)  Slides\.pdf", os.path.basename(pdf)).group(1)
            put(wd, r, 1, u, align="center", font=BOLD); put(wd, r, 2, stem, font=BOLD)
            put(wd, r, 3, "open", link=gh(rel(pdf)))
            for j, (sub, name) in enumerate([("PDFs/Teacher Editions", f"A7 {stem}  Teacher Edition.pdf"),
                                              ("PDFs/Question Banks", f"A7 {stem}  Question Bank.pdf"),
                                              ("PDFs/Question Banks", f"A7 {stem}  Question Bank - Additional.pdf")], 4):
                p = os.path.join(folder, sub, name)
                put(wd, r, j, "open", link=gh(rel(p))) if os.path.exists(p) else put(wd, r, j, "")
            put(wd, r, 7, "folder", link=gh(rel(os.path.join(folder, "Answer Keys")), "tree"))
            r += 1
    for i, w in enumerate([6, 9, 13, 16, 14, 24, 12], 1):
        wd.column_dimensions[get_column_letter(i)].width = w
    wd.freeze_panes = "C2"

    # ------------------------------------------------------------ About
    wa = wb.create_sheet("About")
    lines = [
        ("What this is", BOLD),
        ("The 2026–27 plan for Grade 7 Accelerated (course 1205050): one row per class day from 23 September to 30 April, then one row for the PM3 window (3–28 May), with a link to every document that has been built for that day.", BODY),
        ("", BODY),
        ("The links", BOLD),
        ("Every link opens the file in the GitHub repository. A PDF opens right in the browser; a PowerPoint file shows a download button instead. If GitHub asks you to sign in, use your croix18 account.", BODY),
        ("'Slides (PDF)' is the deck as it prints; 'Slides (PowerPoint)' is the same deck to present from.", BODY),
        ("On an exam day the Slides column links the assessment paper; on a spiral day it links the Unit Review, which goes home as practice (ruling 27a — A7 has no review day).", BODY),
        ("'not built yet' means the unit's package does not exist in the repository yet. Units 5 onward will get links as they are built; this file is regenerated from the plan each time.", BODY),
        ("", BODY),
        ("IXL", BOLD),
        ("Every skill listed is required, to a SmartScore of 67, due at the start of the next class (ruling 28). Where lessons in a row use the same skills they are one assignment, due after the last of them, and the 'IXL due' column already shows that date (4.05 and 4.06 are both due 21 Oct).", BODY),
        ("", BODY),
        ("Where it comes from", BOLD),
        (f"Generated by tools/scope_workbook.py from a7/reference/A7 SCOPE AND SEQUENCE 2026-27.md (itself generated from the plan in tools/scope_calendar.py) and the package folders, at commit {commit()} on {datetime.date.today().strftime('%d %B %Y')}. The plan is edited in scope_calendar.py; this file is never edited by hand.", BODY),
        ("Dates are school days from the plan; the PM3 window (3–28 May) is free of content by design. The county's own 2026–27 sequence is not this file — it is next year's map, transcribed in a7/reference/SCOPE AND SEQUENCE 2026-2027.md.", BODY),
    ]
    for i, (t, f) in enumerate(lines, 1):
        c = wa.cell(row=i, column=1, value=t); c.font = f; c.alignment = Alignment(wrap_text=True, vertical="top")
    wa.column_dimensions["A"].width = 120

    wb.save(out)
    return len(rows), last_row


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "a7", "reference", "A7 Scope and Sequence 2026-27.xlsx")
    n, last = build(out)
    print(f"wrote {out}: {n} periods")
